version: '3.1'
 
services:
  teamcity:
    image: jetbrains/teamcity-server:2017.2.4
    volumes:
      - teamcity-server-datadir:/data/teamcity-server/datadir
      - teamcity-server-logs:/opt/teamcity/logs
    ports:
      - 8111:8111
  teamcity-agent:
    image: localhost:50000/codemazeblog/teamcity-agent-docker-compose:latest
    environment:
      SERVER_URL: http://teamcity:8111
    volumes:
      - teamcity-agent-conf:/data/teamcity_agent/conf
      - /var/run/docker.sock:/var/run/docker.sock
      
volumes:
  teamcity-server-datadir:
  teamcity-server-logs:
  teamcity-agent-conf: